#IFNDEF MODXX_GLOBALS
#DEFINE MODXX_GLOBALS
; Begin global MOD assignments.
; End global MOD assignments.
;
#ENDIF
#IFNDEF MODXX_ASSIGNMENTS
#DEFINE MODXX_ASSIGNMENTS
; Begin MOD-XX assignments.
; End MOD-XX assignments.
;
#ENDIF
#IFNDEF MODXX_CODE
#DEFINE MODXX_CODE
; START MOD-XX - Serial Receive
; END MOD-XX
#ENDIF
